/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Desktop: typeof import('./src/components/svg/desktop.vue')['default']
    Discord: typeof import('./src/components/svg/discord.vue')['default']
    GamerFooter: typeof import('./src/layout/gamer-footer.vue')['default']
    GamerHeader: typeof import('./src/layout/gamer-header.vue')['default']
    Games: typeof import('./src/components/sections/games.vue')['default']
    Highlights: typeof import('./src/components/sections/highlights.vue')['default']
    Influencing: typeof import('./src/components/sections/influencing.vue')['default']
    JoinUs: typeof import('./src/components/sections/join-us.vue')['default']
    Layout: typeof import('./src/layout/layout.vue')['default']
    Medium: typeof import('./src/components/svg/medium.vue')['default']
    Mobile: typeof import('./src/components/svg/mobile.vue')['default']
    News: typeof import('./src/components/sections/news.vue')['default']
    Partners: typeof import('./src/components/sections/partners.vue')['default']
    PartnersBg: typeof import('./src/components/svg/partners-bg.vue')['default']
    Portal: typeof import('./src/components/sections/portal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/svg-icon.vue')['default']
    Telegram: typeof import('./src/components/svg/telegram.vue')['default']
    Twitter: typeof import('./src/components/svg/twitter.vue')['default']
  }
}
