/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dropdown: typeof import('./../components/Dropdown.vue')['default']
    DropdownItem: typeof import('./../components/DropdownItem.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    Game: typeof import('./../components/Game.vue')['default']
    Genesis: typeof import('./../components/Genesis.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    Hero: typeof import('./../components/Hero.vue')['default']
    LottieAnimation: typeof import('./../components/LottieAnimation.vue')['default']
    Meet: typeof import('./../components/Meet.vue')['default']
    Partners: typeof import('./../components/Partners.vue')['default']
    Protocol: typeof import('./../components/Protocol.vue')['default']
    Roadmap: typeof import('./../components/Roadmap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon.vue')['default']
  }
}
